### ISSUE TITLE
提一个新的功能

### ISSUE THREAD

**Issue by EasyChris** [zi6xuan/SmsToEmail#1]
不知道能不能增加一个支持http 请求的接口。

配合 [bark](https://github.com/Finb/Bark) 或者[serverJiang](http://sc.ftqq.com/3.version) 就可以很方便的转发到微信或者app上。而不是等邮件，有时候邮件会有延迟。

**Comment by zi6xuan** [comment]
给微信用户发消息要授权吧，挺麻烦的，Email目前的延迟还算可以接受，但是如果你有简单的http接口发送消息的话开发起来也是很方便的

**Comment by EasyChris** [comment]
对。不需要你微信授权给用户发消息，只需要在app里面增加一个发起http的请求就好了。然后这个http的请求会请求到我的服务器上，其他的鉴权在服务器上完成就好了。你所需要加的，只是一个发起http的请求就好了。

**Comment by zi6xuan** [comment]
那你可以直接源码改一改，很简单的
